apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/luoyingjuntorino/ArgoCD-GitOps
    targetRevision: HEAD
    path: apps # ArgoCD 会扫描该目录下的所有子 app（fastapi-clientinfo、nginx…）

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
